---
- name: Install "{{ package }}" on Debian-based systems
  ansible.builtin.apt:
    name: "{{ package }}"
    state: "{{ state }}"
    update_cache: yes
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Install "{{ package }}" on RedHat-based systems
  ansible.builtin.dnf:
    name: "{{ package }}"
    state: "{{ state }}"
  when: ansible_facts.os_family == "RedHat"

# Fallback if dnf is not available (older systems)
- name: Install "{{ package }}" on older RHEL-based systems using yum
  ansible.builtin.yum:
    name: "{{ package }}"
    state: "{{ state }}"
  when:
  - ansible_facts.os_family == "RedHat"
  - "'dnf' not in ansible_facts.packages"

- name: Start and enable "{{ package }}" service
  ansible.builtin.service:
    name: "{{ package }}"
    state: started
    enabled: true
  become: true
